export const heroes = {
  turtle: {
    id: "turtle",
    name: "turtle",
    dirname: "turtle",
    zones: ["head", "body", "legs", "back", "nose"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 1,
    defenseZonesCount: 2,
  },
  seaWorm: {
    id: "seaWorm",
    name: "sea worm",
    dirname: "sea-worm",
    zones: ["head", "body", "legs", "back", "nose"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 2,
    defenseZonesCount: 1,
  },
  frogFish: {
    id: "frogFish",
    name: "frog-fish",
    dirname: "frog-fish",
    zones: ["head", "body", "legs", "back", "nose"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 2,
    defenseZonesCount: 1,
  },
  jellyfish: {
    id: "jellyfish",
    name: "jellyfish",
    dirname: "jellyfish",
    zones: ["head", "body", "legs", "back", "nose"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 2,
    defenseZonesCount: 1,
  },
};

export const enemies = {
  octopus: {
    id: "octopus",
    name: "octopus",
    dirname: "octopus",
    zones: ["head", "body", "tentacles", "back", "nose"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 1,
    defenseZonesCount: 2,
  },
  shark: {
    id: "shark",
    name: "shark",
    dirname: "shark",
    zones: ["head", "body", "legs", "back", "nose"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 2,
    defenseZonesCount: 1,
  },
};
