export const heroes = {
  turtle: {
    id: "turtle",
    name: "turtle",
    dirname: "turtle",
    zones: ["head", "shell", "legs", "tail"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 1,
    defenseZonesCount: 2,
    critical: 1,
  },
  seaWorm: {
    id: "seaWorm",
    name: "sea worm",
    dirname: "sea-worm",
    zones: ["head", "body", "tail"],
    life: 160,
    damagePower: 7,
    attackZonesCount: 2,
    defenseZonesCount: 1,
    critical: 1,
  },
  frogFish: {
    id: "frogFish",
    name: "frog-fish",
    dirname: "frog-fish",
    zones: ["head", "fins", "belly", "back"],
    life: 140,
    damagePower: 7,
    attackZonesCount: 2,
    defenseZonesCount: 1,
    critical: 1,
  },
  jellyfish: {
    id: "jellyfish",
    name: "jellyfish",
    dirname: "jellyfish",
    zones: ["tentacles", "oral arms", "bell"],
    life: 100,
    damagePower: 5,
    attackZonesCount: 2,
    defenseZonesCount: 2,
    critical: 1,
  },
};

export const enemies = {
  octopus: {
    id: "octopus",
    name: "octopus",
    dirname: "octopus",
    zones: ["head", "front tentacles", "hind tentacles", "beak"],
    life: 150,
    damagePower: 10,
    attackZonesCount: 1,
    defenseZonesCount: 2,
    critical: 1,
  },
  shark: {
    id: "shark",
    name: "shark",
    dirname: "shark",
    zones: ["head", "fins", "gills", "belly", "tail"],
    life: 130,
    damagePower: 5,
    attackZonesCount: 2,
    defenseZonesCount: 1,
    critical: 1,
  },
};
